import { LabelTemplate } from "@/types/label";

export const ELGIN_PRESET_ID   = "elgin-l42pro-3col-28x14";
export const ANEL_PRESET_ID    = "tpl-1778773858958";
export const AMARELA_PRESET_ID = "tpl-1778774578236";

export function elginPreset(): LabelTemplate {
  return {
    id: ELGIN_PRESET_ID,
    name: "Elgin L42PRO 3 colunas 28x15",
    category: "",
    widthMm: 28,
    heightMm: 15,
    marginMm: 0,
    marginLeftMm: 2,
    marginRightMm: 2,
    marginTopMm: 0,
    marginBottomMm: 0,
    paperWidthMm: 94,
    columns: 3,
    columnGapMm: 3,
    rowGapMm: 3,
    safePaddingLeftMm: 1,
    safePaddingRightMm: 1,
    safePaddingTopMm: 1,
    safePaddingBottomMm: 1,
    printRotation: 0,
    columnOrder: "ltr",
    dpi: 203,
    preferredPrinterName: "",
    fontFamily: "Arial, sans-serif",
    fields: [
      {
        key: "descricao",
        visible: true,
        x: 0,
        y: 0.2,
        widthMm: 28,
        heightMm: 2,
        fontSize: 6,
        bold: true,
        align: "center",
        descriptionMode: "first-two-words",
        fontFamily: "Arial, sans-serif",
        color: "#000000",
        scaleX: 1.1,
      },
      {
        key: "barcode",
        visible: true,
        x: 0,
        y: 2.2,
        widthMm: 28,
        heightMm: 8.5,
        fontSize: 7,
        align: "center",
        barcodeFormat: "auto",
        barcodeDisplayValue: true,
        barcodeBarWidth: 0.8,
        barcodeNarrow: 2,
        barcodeWideRatio: 3,
        barcodeTextPosition: "bottom",
        barcodeLineColor: "#000000",
        barcodeTextMargin: 1,
        fontFamily: "Arial, sans-serif",
        color: "#000000",
      },
      {
        key: "precoVarejo",
        visible: true,
        x: 0,
        y: 11.5,
        widthMm: 28,
        heightMm: 3,
        fontSize: 9,
        bold: true,
        label: "R$",
        fontFamily: "Arial, sans-serif",
        align: "center",
        color: "#000000",
        scaleX: 1.1,
      },
      {
        key: "ean",
        visible: false,
        x: 2,
        y: 11,
        widthMm: 24,
        heightMm: 3,
        fontSize: 4,
        align: "center",
        fontFamily: "Arial, sans-serif",
        color: "#000000",
      },
      {
        key: "precoAtacado",
        visible: false,
        x: 2,
        y: 11,
        widthMm: 20,
        heightMm: 3,
        fontSize: 4,
        label: "AT R$",
        fontFamily: "Arial, sans-serif",
        align: "left",
        color: "#000000",
      },
      {
        key: "secao",
        visible: false,
        x: 2,
        y: 11,
        widthMm: 20,
        heightMm: 3,
        fontSize: 4,
        fontFamily: "Arial, sans-serif",
        align: "left",
        color: "#000000",
      },
      {
        key: "estoque",
        visible: false,
        x: 20,
        y: 11,
        widthMm: 6,
        heightMm: 3,
        fontSize: 4,
        fontFamily: "Arial, sans-serif",
        align: "left",
        color: "#000000",
      },
    ],
  };
}

export function anelPreset(): LabelTemplate {
  return {
    id: ANEL_PRESET_ID,
    name: "Etiqueta de Anel",
    category: "Etiqueta de Anel",
    widthMm: 50,
    heightMm: 10,
    marginMm: 0,
    marginLeftMm: 22,
    marginRightMm: 0,
    marginTopMm: 4,
    marginBottomMm: 4,
    paperWidthMm: 74,
    columns: 1,
    columnGapMm: 0,
    rowGapMm: 4,
    safePaddingLeftMm: 2,
    safePaddingRightMm: 2,
    safePaddingTopMm: 1,
    safePaddingBottomMm: 1,
    printRotation: 0,
    columnOrder: "ltr",
    preferredPrinterName: "",
    fontFamily: "Arial, sans-serif",
    fields: [
      {
        key: "descricao",
        visible: true,
        x: 1.3,
        y: 1.2,
        widthMm: 21.6,
        heightMm: 3,
        fontSize: 4,
        bold: true,
        align: "center",
        descriptionMode: "first-two-words",
        fontFamily: "Arial, sans-serif",
        color: "#000000",
        scaleX: 1.55,
      },
      {
        key: "barcode",
        visible: true,
        x: 27.8,
        y: 2.2,
        widthMm: 19.5,
        heightMm: 5.7,
        fontSize: 7,
        align: "center",
        barcodeFormat: "auto",
        barcodeDisplayValue: true,
        barcodeBarWidth: 0.8,
        barcodeNarrow: 2,
        barcodeWideRatio: 3,
        barcodeTextPosition: "bottom",
        barcodeLineColor: "#000000",
        barcodeTextMargin: 1,
        fontFamily: "Arial, sans-serif",
        color: "#000000",
      },
      {
        key: "codigoInterno",
        visible: false,
        x: 2,
        y: 1,
        widthMm: 8,
        heightMm: 3,
        fontSize: 5,
        fontFamily: "Arial, sans-serif",
        align: "left",
        color: "#000000",
      },
      {
        key: "precoVarejo",
        visible: true,
        x: 1.7,
        y: 4.8,
        widthMm: 19.4,
        heightMm: 3.5,
        fontSize: 6,
        bold: true,
        label: "R$",
        fontFamily: "Arial, sans-serif",
        align: "center",
        color: "#000000",
        scaleX: 1.75,
      },
      {
        key: "ean",
        visible: false,
        x: 2,
        y: 11,
        widthMm: 24,
        heightMm: 3,
        fontSize: 4,
        align: "center",
        fontFamily: "Arial, sans-serif",
        color: "#000000",
      },
      {
        key: "precoAtacado",
        visible: false,
        x: 2,
        y: 11,
        widthMm: 20,
        heightMm: 3,
        fontSize: 4,
        label: "AT R$",
        fontFamily: "Arial, sans-serif",
        align: "left",
        color: "#000000",
      },
      {
        key: "secao",
        visible: false,
        x: 2,
        y: 11,
        widthMm: 20,
        heightMm: 3,
        fontSize: 4,
        fontFamily: "Arial, sans-serif",
        align: "left",
        color: "#000000",
      },
      {
        key: "estoque",
        visible: false,
        x: 20,
        y: 11,
        widthMm: 6,
        heightMm: 3,
        fontSize: 4,
        fontFamily: "Arial, sans-serif",
        align: "left",
        color: "#000000",
      },
    ],
  };
}

export function amarelaPreset(): LabelTemplate {
  return {
    id: AMARELA_PRESET_ID,
    name: "Etiqueta Amarela",
    category: "Etiqueta Amarela",
    widthMm: 110,
    heightMm: 30,
    marginMm: 0,
    marginLeftMm: 0,
    marginRightMm: 0,
    marginTopMm: 0,
    marginBottomMm: 0,
    paperWidthMm: 110,
    columns: 1,
    columnGapMm: 0,
    rowGapMm: 0,
    safePaddingLeftMm: 2,
    safePaddingRightMm: 2,
    safePaddingTopMm: 1,
    safePaddingBottomMm: 1,
    printRotation: 0,
    columnOrder: "ltr",
    preferredPrinterName: "",
    fontFamily: "Arial, sans-serif",
    fields: [
      { key: "descricao", visible: true, x: 1.5, y: 1.5, widthMm: 103.8, heightMm: 8, fontSize: 9, bold: true, align: "left", descriptionMode: "full", fontFamily: "Arial, sans-serif", color: "#000000", scaleX: 1.5 },
      { key: "barcode", visible: true, x: 3.3, y: 12.4, widthMm: 43.5, heightMm: 13.7, fontSize: 18, align: "center", barcodeFormat: "auto", barcodeDisplayValue: true, barcodeBarWidth: 1.3, barcodeNarrow: 2, barcodeWideRatio: 3, barcodeTextPosition: "bottom", barcodeLineColor: "#000000", barcodeTextMargin: 2, fontFamily: "Arial, sans-serif", color: "#000000" },
      { key: "codigoInterno", visible: false, x: 2, y: 1, widthMm: 8, heightMm: 3, fontSize: 5, fontFamily: "Arial, sans-serif", align: "left", color: "#000000" },
      { key: "precoVarejo", visible: true, x: 50.6, y: 12.1, widthMm: 55.1, heightMm: 14.4, fontSize: 17, bold: true, label: "R$", fontFamily: "Arial, sans-serif", align: "center", color: "#000000", scaleX: 1.65 },
      { key: "ean", visible: false, x: 2, y: 11, widthMm: 24, heightMm: 3, fontSize: 4, align: "center", fontFamily: "Arial, sans-serif", color: "#000000" },
      { key: "precoAtacado", visible: false, x: 2, y: 11, widthMm: 20, heightMm: 3, fontSize: 4, label: "AT R$", fontFamily: "Arial, sans-serif", align: "left", color: "#000000" },
      { key: "secao", visible: false, x: 2, y: 11, widthMm: 20, heightMm: 3, fontSize: 4, fontFamily: "Arial, sans-serif", align: "left", color: "#000000" },
      { key: "estoque", visible: false, x: 20, y: 11, widthMm: 6, heightMm: 3, fontSize: 4, fontFamily: "Arial, sans-serif", align: "left", color: "#000000" },
    ],
  };
}
