import { LabelTemplate } from "@/types/label";

export const ELGIN_PRESET_ID = "elgin-l42pro-3col-28x14";

export function elginPreset(): LabelTemplate {
  return {
    id: ELGIN_PRESET_ID,
    name: "Elgin L42PRO 3 colunas 28x14",
    category: "Etiqueta branca",
    widthMm: 28,
    heightMm: 13.5,
    marginMm: 0,
    marginLeftMm: 5,
    marginRightMm: 3,
    marginTopMm: 0,
    marginBottomMm: 3,
    paperWidthMm: 100,
    columns: 3,
    columnGapMm: 3,
    rowGapMm: 3,
    safePaddingLeftMm: 2,
    safePaddingRightMm: 2,
    safePaddingTopMm: 1,
    safePaddingBottomMm: 1,
    printRotation: 0,
    columnOrder: "ltr",
    fontFamily: "Arial, sans-serif",
    fields: [
      {
        key: "descricao",
        visible: true,
        x: 3.3,
        y: 1.7,
        widthMm: 10,
        heightMm: 3,
        fontSize: 4,
        bold: true,
        align: "left",
        descriptionMode: "first-word",
      },
      {
        key: "barcode",
        visible: true,
        x: 2.2,
        y: 5.4,
        widthMm: 24.5,
        heightMm: 7.5,
        fontSize: 11,
        align: "left",
        barcodeFormat: "auto",
        barcodeDisplayValue: true,
        barcodeBarWidth: 0.7,
        barcodeNarrow: 2,
        barcodeWideRatio: 3,
        barcodeTextPosition: "bottom",
        barcodeLineColor: "#000000",
        barcodeTextMargin: 1,
      },
      { key: "codigoInterno", visible: false, x: 2, y: 1, widthMm: 8, heightMm: 3, fontSize: 5 },
      { key: "precoVarejo", visible: true, x: 13.1, y: 2.1, widthMm: 12, heightMm: 3, fontSize: 6, bold: true, label: "R$" },
      { key: "ean", visible: false, x: 2, y: 11, widthMm: 24, heightMm: 3, fontSize: 4, align: "center" },
      { key: "precoAtacado", visible: false, x: 2, y: 11, widthMm: 20, heightMm: 3, fontSize: 4, label: "AT R$" },
      { key: "secao", visible: false, x: 2, y: 11, widthMm: 20, heightMm: 3, fontSize: 4 },
      { key: "estoque", visible: false, x: 20, y: 11, widthMm: 6, heightMm: 3, fontSize: 4 },
    ],
  };
}
